- name: Install go 1.16 (Linux)
  become: yes
  snap:
    classic: yes
    channel: 1.16/stable
    name: go
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install go and required tools (MacOSX)
  homebrew:
    name: 
    - go
    - dep
    - glide
  when: ansible_distribution == "MacOSX"

- name: Create go path related directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - ~/Projects
  - ~/Projects/go
  - ~/Projects/go/bin
  - ~/Projects/go/pkg
  - ~/Projects/go/src

- name: Link git configuration
  file:
    src: "{{ playbook_dir }}/config/gorc"
    dest: ~/.gorc
    state: link

- name: Install required go tools (Arch)
  become: yes
  pacman:
    name:
    - dep
    - glide
  when: ansible_distribution == "Archlinux"

- name: Install required go tools (Ubuntu)
  become: yes
  apt:
    name:
    - go-dep
    - golang-glide
  when: ansible_distribution == "Ubuntu"
