docker_aliases_version: 0.4.0
# Version here does not matter too much, because we later manage bin by itself
bin_base_version: 0.7.0
# Version here does not matter too much, because topgrade upgrades itself on each run
topgrade_base_version: 6.9.1
