- name: Install dotfiles loader
  git:
    repo: https://github.com/schnatterer/dotfiles-loader
    dest: ~/.dotfiles-loader
    update: no


# This leads to dotfiles "bootstrap" script running non-interactively
- name: Render git configuration
  template:
    src: "{{ playbook_dir }}/config/gitconfig.j2"
    dest: ~/.dotfiles-loader/git/gitconfig.local
    mode: 0600

- name: Bootstrap dotfiles
  # B as in "Backup all"
  shell: echo B | dotfiles_repo="{{ dotfilesRepo }}" ~/.dotfiles-loader/script/bootstrap
