- name: Install screen recording packages (Ubuntu)
  become: yes
  apt:
    name:
    # gif image optimization
    - gifsicle 
    # gif screen recording
    - peek
    # video screen recording
    - kazam
  when: ansible_distribution == "Ubuntu"
