- name: Install vscode (Arch)
  become: yes
  snap:
    name: code
    classic: yes
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install vscode (Ubuntu)
  become: yes
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Remove deprecated vscode (Linux)
  become: yes
  snap:
    name: vscode
    classic: yes
    state: absent
  when: ansible_system == "Linux"

- name: Install vscode (MacOSX)
  homebrew_cask:
    name: visual-studio-code
  when: ansible_distribution == "MacOSX"

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  with_items:
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-azuretools.vscode-docker
  - EditorConfig.EditorConfig
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - vscoss.vscode-ansible
  - k--kato.intellij-idea-keybindings
  - mauve.terraform
  - marcostazi.vs-code-vagrantfile
  - redhat.vscode-yaml
  - jebbs.plantuml
  - mrcrowl.hg
  - msjsdiag.debugger-for-chrome
  - ms-vsliveshare.vsliveshare
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
