- name: Check directory (Arch)
  stat:
    path: /usr/local/google-cloud-sdk
  register: gcloud
  changed_when: False

- name: Download gcloud package (Arch)
  get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-249.0.0-linux-x86_64.tar.gz
    dest: /tmp/google-cloud-sdk.tar.gz
  when: gcloud.stat.exists == False

- name: Unarchive gcloud package (Arch)
  become: yes
  unarchive:
    src: /tmp/google-cloud-sdk.tar.gz
    dest: /usr/local
    remote_src: yes
  when: gcloud.stat.exists == False

- name: Remove downloaded package (Arch)
  file:
    path: /tmp/google-cloud-sdk.tar.gz
    state: absent
  when: gcloud.stat.exists == False
