- name: Install gcloud gpg key (Ubuntu)
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: Capture lsb release (Ubuntu)
  shell: lsb_release -cs
  register: lsbrelease
  changed_when: False

- name: Install docker apt repository (Ubuntu)
  become: yes
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main

- name: Install google-cloud-sdk package (Ubuntu)
  become: yes
  apt:
    name: google-cloud-sdk
