- name: capture installed helm version
  shell: helm version -c --short | awk '{print $2}' | awk -F'+' '{print $1}' | sed 's/v//g'
  register: helm
  changed_when: False

- name: download and unarchive
  unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
  when: helm.stdout != helm_version

- name: install helm
  become: yes
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0755
  when: helm.stdout != helm_version

- name: remove temporary files
  file:
    path: /tmp/linux-amd64
    state: absent
  when: helm.stdout != helm_version
