- name: capture installed kustomize version
  shell: kustomize version | awk -F ':' '{print $3}' | awk '{print $1}'
  register: kustomize
  changed_when: False

- name: Remove old installation
  become: yes
  file:
    path: /usr/local/bin/kustomize
    state: absent
  when: kustomize.stdout != kustomize_version

- name: install kustomize
  become: yes
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/v{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_amd64
    dest: /usr/local/bin/kustomize
    mode: 0755
    owner: root
    group: root
  when: kustomize.stdout != kustomize_version
