- name: Install k8s tools (Linux)
  include: linux.yml
  when: ansible_system == "Linux"

- name: Install k8s tools (MacOSX)
  include: osx.yml
  when: ansible_distribution == "MacOSX"

- name: Install kube-cleaner
  include: kube-cleaner.yml
