- name: Install k8s tools (Linux)
  include: linux.yml
  when: ansible_system == "Linux"

- name: Install k8s tools (MacOSX)
  include: osx.yml
  when: ansible_distribution == "MacOSX"

- name: Install kube-cleaner
  include: kube-cleaner.yml

- name: Install k9s
  shell: $HOME/.local/bin/bin list | grep {{ item }} || $HOME/.local/bin/bin install {{ item }}
  with_items:
    - github.com/derailed/k9s
    - github.com/dty1er/kubecolor
    - github.com/rancher/k3d
