- name: Install git (Arch)
  become: yes
  pacman:
    name: git
  when: ansible_distribution == "Archlinux"

- name: Install git (Ubuntu)
  become: yes
  apt:
    name: git
  when: ansible_distribution == "Ubuntu"

- name: Install git (MacOSX)
  homebrew:
    name: git
  when: ansible_distribution == "MacOSX"

- name: Check if diff-so-fancy is installed
  stat:
    path: /usr/local/bin/diff-so-fancy
  register: diffsofancy

- name: Render git configuration
  template:
    src: "{{ playbook_dir }}/config/gitconfig.j2"
    dest: ~/.gitconfig
    mode: 0600
