- name: Install git (Arch)
  become: yes
  pacman:
    name: 
    - git
    - git-crypt
  when: ansible_distribution == "Archlinux"

- name: Install git related tools (Ubuntu)
  become: yes
  apt:
    name: 
    - git
    - git-crypt
  when: ansible_distribution == "Ubuntu"

- name: Install git (MacOSX)
  homebrew:
    name: 
    - git
    - git-crypt
    - gh
  when: ansible_distribution == "MacOSX"

- name: Check gh client version (Ubuntu)
  shell: gh --version | head -1 | awk '{print $3}'
  register: gh
  changed_when: False
  when: ansible_distribution == "Ubuntu"

- name: Install GitHub Client (Ubuntu)
  become: yes
  apt:
    deb: https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.deb
  when: ansible_distribution == "Ubuntu" and gh.stdout != gh_version

- name: Check if diff-so-fancy is installed
  stat:
    path: /usr/local/bin/diff-so-fancy
  register: diffsofancy

# Note that gitconfig is written in dotfiles

