- name: Capture bat version (Ubuntu)
  shell: bat --version | awk '{print $2}'
  register: bat
  changed_when: False
  when: ansible_distribution == "Ubuntu"

- name: Install bat (Ubuntu)
  become: yes
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb
  when: ansible_distribution == "Ubuntu" and bat.stdout != bat_version

- name: Install bat (Arch)
  become: yes
  pacman:
    name: bat
  when: ansible_distribution == "Archlinux"

- name: Install bat (MacOSX)
  homebrew:
    name:
    - bat
  when: ansible_distribution == "MacOSX"

- name: Create bat configuration directory
  file:
    path: ~/.config/bat
    state: directory

- name: Link bat configuration
  file:
    src: "{{ playbook_dir }}/config/bat-config"
    dest: ~/.config/bat/config
    state: link
