- name: Install bat (Ubuntu)
  become: yes
  apt:
    name: bat
  when: ansible_distribution == "Ubuntu"

- name: Install bat (Arch)
  become: yes
  pacman:
    name: bat
  when: ansible_distribution == "Archlinux"

- name: Install bat (MacOSX)
  homebrew:
    name:
    - bat
  when: ansible_distribution == "MacOSX"

- name: Create bat configuration directory
  file:
    path: ~/.config/bat
    state: directory

- name: Link bat configuration
  file:
    src: "{{ playbook_dir }}/config/bat-config"
    dest: ~/.config/bat/config
    state: link
