- name: Install gopass (Arch)
  become: yes
  pacman:
    name: gopass
  when: ansible_distribution == "Archlinux"

- name: Install gopass (Ubuntu)
  shell: $HOME/.local/bin/bin list | grep {{ item }} || $HOME/.local/bin/bin install {{ item }}
  with_items:
    - github.com/gopasspw/gopass
  when: ansible_distribution == "Ubuntu"
