- name: Install cli tools from repository (Ubuntu)
  become: yes
  apt:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - ncdu
  when: ansible_distribution == "Ubuntu"

- name: Install cli tools from repository (Arch)
  become: yes
  pacman:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - ncdu
  when: ansible_distribution == "Archlinux"

- name: Install cli tools from repository (MacOSX)
  homebrew:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - gotop
    - ctop
    - cfssl
    - gopass
    - vegeta
    - ncdu
  when: ansible_distribution == "MacOSX"

- name: Install bat
  include: bat.yml

- name: Install gotop
  include: gotop.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install ctop
  include: ctop.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install cfssl
  include: cfssl.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install gopass
  include: gopass.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install vegeta
  include: vegeta.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install aliases
  include: aliases.yml
