- name: Capture vegeta version
  shell: vegeta --version | grep '^Version' | awk '{print $2}'
  register: vegeta
  changed_when: False

- name: Create temporary download location
  file:
    path: /tmp/vegeta
    state: directory
  when: vegeta.stdout != vegeta_version

- name: Download vegeta
  unarchive:
    src: https://github.com/tsenart/vegeta/releases/download/v{{vegeta_version}}/vegeta_{{vegeta_version}}_linux_amd64.tar.gz
    dest: /tmp/vegeta
    remote_src: yes
  when: vegeta.stdout != vegeta_version

- name: Copy vegeta binary
  become: yes
  copy:
    src: /tmp/vegeta/vegeta
    dest: /usr/local/bin/vegeta
    mode: 0755
    owner: root
    group: root
  when: vegeta.stdout != vegeta_version

- name: Remove temporary download location
  file:
    path: /tmp/vegeta
    state: absent
  when: vegeta.stdout != vegeta_version
