# We could query latest java 8 or 11 if necessary, like this.
# curl https://api.sdkman.io/2/candidates/java/linuxx64/versions/list?current=&installed= | grep hs-adpt | grep 11. | head -n1 | awk '{print $8}'
# Or we just install latest. Which might be enough. We can still install more JDKs later, if necessary.
- name: Install latest sdkman, java, groovy, gradle, maven
  include_role:
    name: Comcast.sdkman
  vars: 
      sdkman_install_packages:
        - { candidate: maven }
        - { candidate: gradle }
        - { candidate: groovy }
        - { candidate: java }
