- name: Install gcloud (Ubuntu)
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install gcloud (Arch)
  include: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Install kubectl
  become: yes
  shell: gcloud components install kubectl --quiet
  args:
    creates: /usr/local/google-cloud-sdk/bin/kubectl
  when: ansible_distribution != "Ubuntu"

- name: Install kubectl 
  become: yes
  snap:
    classic: yes
    name: kubectl
  when: ansible_distribution == "Ubuntu"

- name: Install kubectx
  include: kubectx.yml

- name: Install helm
  include: helm.yml
