- name: Install tmux and required dependencies (Arch)
  become: yes
  pacman:
    name: tmux
  when: ansible_distribution == "Archlinux"

- name: Install tmux and required dependencies (Ubuntu)
  become: yes
  apt:
    name: tmux
  when: ansible_distribution == "Ubuntu"

- name: Install tmux and required dependencies (MacOSX)
  homebrew:
    name: tmux
  when: ansible_distribution == "MacOSX"

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
