- name: Install node (Linux)
  become: yes
  snap:
    name: node
    classic: yes
    channel: 12/stable
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Remove node 10 (MacOSX)
  homebrew:
    name: node@10
    state: absent
  when: ansible_distribution == "MacOSX"

- name: Install node and yarn (MacOSX)
  homebrew:
    name: 
    - node
    - yarn
  when: ansible_distribution == "MacOSX"

- name: Install yarn
  become: yes
  npm:
    name: yarn
    global: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install global npm packages
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
  - colortest
  - prettier
  - create-react-app
  - tldr
