- name: Install vim (Arch)
  become: yes
  pacman:
    name: vim
  when: ansible_distribution == "Archlinux"

- name: Install vim (Ubuntu)
  become: yes
  apt:
    name: vim
  when: ansible_distribution == "Ubuntu"

- name: Install vim (MacOSX)
  homebrew:
    name: vim
  when: ansible_distribution == "MacOSX"

- name: install vim runtime
  git:
    repo: https://github.com/amix/vimrc
    dest: ~/.vim_runtime
    update: no

- name: install wal theme for vim
  git:
    repo: https://github.com/dylanaraps/wal.vim
    dest: ~/.vim_runtime/my_plugins/wal.vim
    update: no

- name: install nord theme for vim
  git:
    repo: https://github.com/arcticicestudio/nord-vim
    dest: ~/.vim_runtime/my_plugins/nord-vim
    update: no

- name: Link vimrc configuration
  file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
  - vimrc
