name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  exec:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.4

      # Provide required binaries
      # fc-cache (fontconfig)
      # gsettings (gnome)
      - name: install
        run: sudo apt-get update && sudo apt-get install -y ansible unzip fontconfig gnome-core snapd snap-confine

      # Uninstall gh in order to avoid error: "A later version is already installed"
      - name: Uninstall preconfigured github cli
        run: sudo apt-get remove gh

      - name: create vars.yaml
        run: |
          cat << EOF > vars.yml
          mail: some@o.ne
          displayName: Some one
          gpgKey: "abcdef"
          EOF

      - name: Initial smoke test
        env:
          # Avoid hitting rate limit for bin
          # https://github.com/marcosnils/bin/tree/74bf#i-used-bin-and-i-got-rate-limited-by-github-what-can-i-do
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./devbox -e ansible_become_pass=''

      # Make sure the playbook also succeeds on incremental run
      - name: Incremental smoke test
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./devbox -e ansible_become_pass=''

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # defaults: schedule and ref types
          # Additional: Set sha tag for each image
          # And: Main branch is latest for now 
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=,format=short
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
